### PR TITLE
Extend Testing of Routes Controller Methods for Machine Network Interfaces

### LINKED ISSUE #252: Extend Testing of Routes Controller Methods for `Machine` Network Interfaces
### Description

In our continuous effort to improve the robustness of our cloud provider, it has been observed that our current test suite for the routes controller methods could benefit from additional coverage. Specifically, we would like to add tests for `Machine` instances that reference both ephemeral and static `NetworkInterface` instances.

### Feature Benefits

Expanding our test coverage in this manner will provide several benefits:

1. **Increased Confidence**: Ensuring that our routes controller methods handle all `Machine` configurations correctly increases our confidence in the system's robustness.
2. **Reduced Risk of Regressions**: With more comprehensive test coverage, we reduce the risk of introducing bugs or regressions when changing the codebase.
3. **Improved Documentation**: Detailed test cases can serve as practical examples of how the system should handle various `Machine` configurations.

### Proposed Solution

We propose to improve our test suite by:

- Writing new test cases specifically for `Machine` instances that reference both ephemeral and static `NetworkInterface` instances.
- Refactoring existing test cases to cover these `Machine` instances, if feasible.

### PR DESCRIPTION
**Pull request by sujeet01**
- Extend routes tests to handle `Machine` instances that reference both ephemeral and static `NetworkInterface` instances Fixes #252
- Fix typos

### CODE REVIEW

File: pkg/cloudprovider/onmetal/routes_test.go [hunk 1]
```diff
@@ -50,7 +51,7 @@ var _ = Describe("Routes", func() {
 			ObjectMeta: metav1.ObjectMeta{
```
Comment (Rohit-0505) [inline pkg/cloudprovider/onmetal/routes_test.go:51]: @sujeet01 Can we move the machine and node object creation in `BeforeEach` block to avoid the repetition?

**Review by Rohit-0505 — CHANGES_REQUESTED** [review]

File: pkg/cloudprovider/onmetal/routes_test.go (hunk 1 above)
Comment (sujeet01) [reply pkg/cloudprovider/onmetal/routes_test.go:51]: Done.

**Comment by sujeet01** [comment]
@afritzler Could you please have a look and let me know if you have any suggestions.

**Review by afritzler — APPROVED** [review]
